### ISSUE TITLE
about data from IEDB

### ISSUE THREAD

**Issue by jiaweizhang123456** [Lee-CBG/ATM-TCR#13]
I am wondering how to confirm that all TCR-PMHC pairs' labels are all 1 in your search settings.(IEDB dataset)

**Comment by cai-michael** [comment]
Hi @jiaweizhang123456, we selected only "positive outcomes" in the Assay settings. According to IEDB if no binding outcome is reported the assay is reported as negative so these should only be assays where binding was observed and explicitly noted. Though due to the mixed granularity between assay and binary nature of our model we don't differentiate between the strength of the positive binding responses and just label them as "binding".

https://help.iedb.org/hc/en-us/articles/360059101311-What-does-positive-high-intermediate-low-mean-in-the-assay-description-column-

**Comment by jiaweizhang123456** [comment]
Thank you very much for your reply！
